init -1 python:
    map_images = {
        ### spots
        "spot_10801": "map/spot_10801.png",
        "spot_10802": "map/spot_10802.png",
        "spot_10803": "map/spot_10803.png",
        "spot_10804": "map/spot_10804.png",
        "spot_10805": "map/spot_10805.png",
        "spot_10806": "map/spot_10806.png",
        "spot_10807": "map/spot_10807.png",
        "spot_10808": "map/spot_10808.png",
        "spot_10801_h": "map/spot_10801_h.png",
        "spot_10802_h": "map/spot_10802_h.png",
        "spot_10803_h": "map/spot_10803_h.png",
        "spot_10804_h": "map/spot_10804_h.png",
        "spot_10805_h": "map/spot_10805_h.png",
        "spot_10806_h": "map/spot_10806_h.png",
        "spot_10807_h": "map/spot_10807_h.png",
        "spot_10808_h": "map/spot_10808_h.png",

        "spot_10801_b": "map/spot_10801_b.png",
        "spot_10802_b": "map/spot_10802_b.png",
        "spot_10803_b": "map/spot_10803_b.png",
        "spot_10804_b": "map/spot_10804_b.png",
        "spot_10805_b": "map/spot_10805_b.png",
        "spot_10806_b": "map/spot_10806_b.png",
        "spot_10807_b": "map/spot_10807_b.png",
        "spot_10808_b": "map/spot_10808_b.png",

        "label_spot_10801": "map/label_spot_10801.png",
        "label_spot_10802": "map/label_spot_10802.png",
        "label_spot_10803": "map/label_spot_10803.png",
        "label_spot_10804": "map/label_spot_10804.png",
        "label_spot_10805": "map/label_spot_10805.png",
        "label_spot_10806": "map/label_spot_10806.png",
        "label_spot_10807": "map/label_spot_10807.png",
        "label_spot_10808": "map/label_spot_10808.png",

        "sound_bgm_main": "map_intro.ogg",
        "sound_bgm_loop": "map_loop.ogg"
    }

    map_images_before_boss = {
        ### background
        "bg_base_back": "map/bg_base_back.png",
        "bg_hand": "map/bg_hand.png",
        ### background objects
        "fg_particle": "map/fg_particle.png",
        "fg_particle_flip": "map/fg_particle_flip.png",
        "bg_particle": "map/bg_particle.png",
        "bg_crystal": "map/bg_crystal.png",
        "bg_obj_01": "map/bg_obj_01.png",
        "bg_obj_03": "map/bg_obj_03.png",
        "bg_obj_05": "map/bg_obj_05.png",
        "bg_obj_06": "map/bg_obj_06.png",
        "bg_obj_08": "map/bg_obj_08.png",
        "bg_obj_09": "map/bg_obj_09.png",
        "bg_obj_10": "map/bg_obj_10.png",
        "bg_obj_11": "map/bg_obj_11.png",
        "bg_obj_12": "map/bg_obj_12.png",
        "bg_obj_13": "map/bg_obj_13.png",
        "bg_obj_14": "map/bg_obj_14.png",
        "bg_obj_15": "map/bg_obj_15.png",
        "bg_obj_16": "map/bg_obj_16.png",
    }

    map_images_boss = {
        ### background
        "bg_base_back": "map/bg_base_back.png",
        ### background objects
        "fg_particle": "map/fg_particle.png",
        "fg_particle_flip": "map/fg_particle_flip.png",
        "bg_particle": "map/bg_particle.png",
        "bg_crystal": "map/bg_crystal.png",
        "bg_obj_01": "map/bg_obj_01.png",
        "bg_obj_03": "map/bg_obj_03.png",
        "bg_obj_05": "map/bg_obj_05.png",
        "bg_obj_06": "map/bg_obj_06.png",
        "bg_obj_08": "map/bg_obj_08.png",
        "bg_obj_09": "map/bg_obj_09.png",
        "bg_obj_10": "map/bg_obj_10.png",
        "bg_obj_11": "map/bg_obj_11.png",
        "bg_obj_12": "map/bg_obj_12.png",
        "bg_obj_13": "map/bg_obj_13.png",
        "bg_obj_14": "map/bg_obj_14.png",
        "bg_obj_15": "map/bg_obj_15.png",
        "bg_obj_16": "map/bg_obj_16.png",
    }

    loading_images = {
        "10801": ["loading/loading_01.png"],
        "10802": ["loading/loading_02.png"],
        "10803": ["loading/loading_03.png"],
        "10804": ["loading/loading_04.png"],
        "10805": ["loading/loading_05.png"],
        "10806": ["loading/loading_06.png"],
        "10807": ["loading/loading_07.png"],
        "10808": ["loading/loading_08.png"]
    }

    background_images = {
        "grail_mud": "bg/grail_mud.png",
        "castle_01_day": "bg/castle_01_day.png",
        "castle_01_night": "bg/castle_01_night.png",
        "town_01": "bg/town_01.png",
        "field_01_night": "bg/field_01_night.png",
        "field_01_dusk": "bg/field_01_dusk.png",
        "rome_dusk": "bg/rome_dusk.png",
        "rome_night": "bg/rome_night.png",
        "foggy_london": "bg/foggy_london.png",
        "foggy_london_2": "bg/foggy_london_2.png",
        "stormy_seas": "bg/stormy_seas.png",
        "stormy_seas_2": "bg/stormy_seas_2.png",
        "calm_seas": "bg/calm_seas.png",
        "clear_london": "bg/clear_london.png",
        "america_night": "bg/america_night.png",
        "dustbowl_plains": "bg/dustbowl_plains.png",
        "dustbowl_town": "bg/dustbowl_town.png",
        "jerus_boss": "bg/jerus_boss.png",
        "desert": "bg/desert.png",
        "jerus_day": "bg/jerus_day.png",
        "babylon_day": "bg/babylon_day.png",
        "lilim_1": "bg/lilim_1.png",
        "lilim_2": "bg/lilim_2.png",
        "boss_01": "bg/boss_01.png",
        "boss_01_full": "bg/boss_01_full.png",
        "boss_02": "bg/boss_02.png",
        "boss_02_full": "bg/boss_02_full.png",
        "boss_03": "bg/boss_03.png",
        "boss_03_full": "bg/boss_03_full.png",
        "boss_04_full": "bg/boss_04_full.png",
        "final_boss": "bg/final_boss.png",
        "ending_m": "bg/ending_m.png",
        "ending_f": "bg/ending_f.png",
        "ruins_day": "bg/ruins_day.png"
    }

    music_to_download = {
        "642_1": [
            "map_orleans_intro.ogg",
            "map_orleans_loop.ogg"
        ],
        "642_4": [
            "map_orleans_intro.ogg",
            "map_orleans_loop.ogg"
        ],
        "643_1": [
            "map_septem_intro.ogg",
            "map_septem_loop.ogg"
        ],
        "643_4": [
            "map_septem_intro.ogg",
            "map_septem_loop.ogg"
        ],
        "644_1": [
            "map_okeanos_intro.ogg",
            "map_okeanos_loop.ogg"
        ],
        "644_4": [
            "map_okeanos_intro.ogg",
            "map_okeanos_loop.ogg"
        ],
        "645_1": [
            "map_london_intro.ogg",
            "map_london_loop.ogg",
            "demon_pillar_intro.ogg",
            "demon_pillar_loop.ogg"
        ],
        "645_4": [
            "map_london_intro.ogg",
            "map_london_loop.ogg"
        ],
        "646_0": [
            "map_america_intro.ogg",
            "map_america_loop.ogg"
        ],
        "646_1": [
            "map_america_intro.ogg",
            "map_america_loop.ogg"
        ],
        "646_4": [
            "map_america_intro.ogg",
            "map_america_loop.ogg"
        ],
        "647_0": [
            "map_lostj_intro.ogg",
            "map_lostj_loop.ogg"
        ],
        "647_0": [
            "map_lostj_intro.ogg",
            "map_lostj_loop.ogg",
            "jacques_intro.ogg",
            "jacques_loop.ogg"
        ],
        "647_1": [
            "map_lostj_intro.ogg",
            "map_lostj_loop.ogg",
            "jacques_intro.ogg",
            "jacques_loop.ogg"
        ],
        "647_4": [
            "map_lostj_intro.ogg",
            "map_lostj_loop.ogg"
        ],
        "648_0": [
            "map_babylon_intro.ogg",
            "map_babylon_loop.ogg",
            "battle_babylon_intro.ogg",
            "battle_babylon_loop.ogg"
        ],
        "648_1": [
            "draco_pre_intro.ogg",
            "draco_pre_loop.ogg",
            "draco_intro.ogg",
            "draco_loop.ogg",
        ],
        "648_4": [
            "map_babylon_intro.ogg",
            "map_babylon_loop.ogg",
            "lilim_battle_intro.ogg",
            "lilim_battle_loop.ogg",
        ],
        "648_4": [
            "map_babylon_intro.ogg",
            "map_babylon_loop.ogg",
            "lilim_battle_intro.ogg",
            "lilim_battle_loop.ogg",
        ],
        "649_0": [
            "lilim_battle_intro.ogg",
            "lilim_battle_loop.ogg",
        ],
        "649_1": [
            "beastvis_intro.ogg",
            "beastvis_loop.ogg",
        ],
        "649_6": [
            "ending_intro.ogg",
            "ending_loop.ogg",
            "credits.ogg"
        ]
    }

    backgrounds_to_download = {
        "intro": ["grail_mud"],
        "642_0": [],
        "642_1": [
            "castle_01_night",
            "field_01_dusk",
            "boss_01"
        ],
        "642_4": [
            "boss_01_full",
            "castle_01_night"
        ],
        "643_0": [],
        "643_1": [
            "boss_02",
            "rome_night"
        ],
        "643_4": [
            "boss_02_full",
            "rome_dusk"
        ],
        "644_0": [],
        "644_1": [
            "boss_03",
            "stormy_seas",
            "stormy_seas_2"
        ],
        "644_4": [
            "boss_03_full",
            "calm_seas"
        ],
        "645_0": [],
        "645_1": [
            "boss_04_full",
            "foggy_london",
            "foggy_london_2"
        ],
        "645_4": [
            "boss_04_full",
            "clear_london"
        ],
        "646_0": [],
        "646_1": [
            "america_night"
        ],
        "646_4": [
            "dustbowl_town"
        ],
        "647_0": [
            "jerus_day",
            "jerus_boss"
            ],
        "647_1": [
            "jerus_boss"
        ],
        "647_4": [
            "desert"
        ],
        "648_0": [
            "grail_mud",
            "babylon_day"
        ],
        "648_1": [
            "grail_mud",
        ],
        "648_4": [
            "babylon_day",
            "lilim_1"
        ],
        "649_0": [
            "lilim_1"
        ],
        "649_1": [
            "lilim_2",
            "final_boss"
        ],
        "649_6_m": [
            "ruins_day",
            "ending_m"
        ],
        "649_6_f": [
            "ruins_day",
            "ending_f"
        ]
    }

    chara_sprites = {
        "merlin_2_normal": "sprites/merlin_2_normal.png",
        "arthur_2_normal": "sprites/arthur_2_normal.png",
        "merlin_2_silhouette": "sprites/merlin_2_silhouette.png",
        "arthur_2_silhouette": "sprites/arthur_2_silhouette.png",
        "first_hassan_2_silhouette": "sprites/first_hassan_2_silhouette.png",
        "noah_3_silhouette": "sprites/noah_3_silhouette.png",
        "altera_2_joy": "sprites/altera_2_joy.png",
        "altera_2_normal": "sprites/altera_2_normal.png",
        "amadeus_2_joy": "sprites/amadeus_2_joy.png",
        "amadeus_2_shy": "sprites/amadeus_2_shy.png",
        "arjuna_2_anger": "sprites/arjuna_2_anger.png",
        "arjuna_2_joy": "sprites/arjuna_2_joy.png",
        "arjuna_2_normal": "sprites/arjuna_2_normal.png",
        "arjuna_2_shout": "sprites/arjuna_2_shout.png",
        "arjuna_2_sorrow": "sprites/arjuna_2_sorrow.png",
        "arthur_2_8": "sprites/arthur_2_8.png",
        "arthur_2_anger": "sprites/arthur_2_anger.png",
        "arthur_2_joy": "sprites/arthur_2_joy.png",
        "arthur_2_shout": "sprites/arthur_2_shout.png",
        "artoria_2_anger": "sprites/artoria_2_anger.png",
        "artoria_2_normal": "sprites/artoria_2_normal.png",
        "artoria_2_sorrow": "sprites/artoria_2_sorrow.png",
        "atalante_1_normal": "sprites/atalante_1_normal.png",
        "beast_vis_1_0": "sprites/beast_vis_1_0.png",
        "beast_vis_1_7": "sprites/beast_vis_1_7.png",
        "beast_vis_1_anger": "sprites/beast_vis_1_anger.png",
        "beast_vis_1_joy": "sprites/beast_vis_1_joy.png",
        "beast_vis_1_normal": "sprites/beast_vis_1_normal.png",
        "beast_vis_1_shy": "sprites/beast_vis_1_shy.png",
        "beast_vis_1_sorrow": "sprites/beast_vis_1_sorrow.png",
        "blackbeard_3_anger": "sprites/blackbeard_3_anger.png",
        "blackbeard_3_joy": "sprites/blackbeard_3_joy.png",
        "blackbeard_3_normal": "sprites/blackbeard_3_normal.png",
        "blackbeard_3_shout": "sprites/blackbeard_3_shout.png",
        "blackbeard_3_sorrow": "sprites/blackbeard_3_sorrow.png",
        "boudica_2_joy": "sprites/boudica_2_joy.png",
        "boudica_2_normal": "sprites/boudica_2_normal.png",
        "boudica_2_shout": "sprites/boudica_2_shout.png",
        "boudica_2_sorrow": "sprites/boudica_2_sorrow.png",
        "caesar_2_joy": "sprites/caesar_2_joy.png",
        "caesar_2_shout": "sprites/caesar_2_shout.png",
        "caligula_2_anger": "sprites/caligula_2_anger.png",
        "caligula_2_shout": "sprites/caligula_2_shout.png",
        "carmilla_1_normal": "sprites/carmilla_1_normal.png",
        "cu_chulainn_alter_1_joy": "sprites/cu_chulainn_alter_1_joy.png",
        "cu_chulainn_alter_1_normal": "sprites/cu_chulainn_alter_1_normal.png",
        "cu_chulainn_alter_1_shout": "sprites/cu_chulainn_alter_1_shout.png",
        "cu_chulainn_alter_shadow_1_shadow": "sprites/cu_chulainn_alter_shadow_1_shadow.png",
        "cursed_arm_3_normal": "sprites/cursed_arm_3_normal.png",
        "cursed_arm_3_shout": "sprites/cursed_arm_3_shout.png",
        "da_vinci_2_joy": "sprites/da_vinci_2_joy.png",
        "da_vinci_2_normal": "sprites/da_vinci_2_normal.png",
        "da_vinci_2_shout": "sprites/da_vinci_2_shout.png",
        "deon_2_anger": "sprites/deon_2_anger.png",
        "deon_2_shout": "sprites/deon_2_shout.png",
        "drake_2_anger": "sprites/drake_2_anger.png",
        "drake_2_joy": "sprites/drake_2_joy.png",
        "drake_2_normal": "sprites/drake_2_normal.png",
        "drake_2_shout": "sprites/drake_2_shout.png",
        "drake_2_sorrow": "sprites/drake_2_sorrow.png",
        "elisabeth_1_joy": "sprites/elisabeth_1_joy.png",
        "elisabeth_1_shout": "sprites/elisabeth_1_shout.png",
        "elisabeth_1_sorrow": "sprites/elisabeth_1_sorrow.png",
        "enkidu_2_joy": "sprites/enkidu_2_joy.png",
        "enkidu_2_normal": "sprites/enkidu_2_normal.png",
        "first_hassan_2_anger": "sprites/first_hassan_2_anger.png",
        "first_hassan_2_joy": "sprites/first_hassan_2_joy.png",
        "first_hassan_2_normal": "sprites/first_hassan_2_normal.png",
        "first_hassan_2_shout": "sprites/first_hassan_2_shout.png",
        "first_hassan_2_sorrow": "sprites/first_hassan_2_sorrow.png",
        "georgios_3_anger": "sprites/georgios_3_anger.png",
        "georgios_3_joy": "sprites/georgios_3_joy.png",
        "georgios_3_shout": "sprites/georgios_3_shout.png",
        "gilgamesh_2_anger": "sprites/gilgamesh_2_anger.png",
        "gilgamesh_2_joy": "sprites/gilgamesh_2_joy.png",
        "gilgamesh_2_normal": "sprites/gilgamesh_2_normal.png",
        "gilgamesh_2_shout": "sprites/gilgamesh_2_shout.png",
        "gilgamesh_2_shy": "sprites/gilgamesh_2_shy.png",
        "gilgamesh_2_sorrow": "sprites/gilgamesh_2_sorrow.png",
        "gilles_de_rais_2_joy": "sprites/gilles_de_rais_2_joy.png",
        "heracles_1_shout": "sprites/heracles_1_shout.png",
        "jack_2_joy": "sprites/jack_2_joy.png",
        "jack_2_normal": "sprites/jack_2_normal.png",
        "jacques_de_molay_1_10": "sprites/jacques_de_molay_1_10.png",
        "jacques_de_molay_1_17": "sprites/jacques_de_molay_1_17.png",
        "jacques_de_molay_1_20": "sprites/jacques_de_molay_1_20.png",
        "jacques_de_molay_1_anger": "sprites/jacques_de_molay_1_anger.png",
        "jacques_de_molay_1_joy": "sprites/jacques_de_molay_1_joy.png",
        "jacques_de_molay_1_normal": "sprites/jacques_de_molay_1_normal.png",
        "jacques_de_molay_1_shout": "sprites/jacques_de_molay_1_shout.png",
        "jacques_de_molay_1_sorrow": "sprites/jacques_de_molay_1_sorrow.png",
        "jacques_de_molay_shadow_1_shadow": "sprites/jacques_de_molay_shadow_1_shadow.png",
        "jeanne_alter_2_shout": "sprites/jeanne_alter_2_shout.png",
        "jeanne_alter_2_shy": "sprites/jeanne_alter_2_shy.png",
        "jeanne_darc_2_anger": "sprites/jeanne_darc_2_anger.png",
        "jeanne_darc_2_normal": "sprites/jeanne_darc_2_normal.png",
        "karna_2_joy": "sprites/karna_2_joy.png",
        "karna_2_normal": "sprites/karna_2_normal.png",
        "karna_2_sorrow": "sprites/karna_2_sorrow.png",
        "kiyohime_2_shout": "sprites/kiyohime_2_shout.png",
        "lancelot_2_normal": "sprites/lancelot_2_normal.png",
        "lancelot_2_shout": "sprites/lancelot_2_shout.png",
        "leonidas_i_2_joy": "sprites/leonidas_i_2_joy.png",
        "leonidas_i_2_normal": "sprites/leonidas_i_2_normal.png",
        "leonidas_i_2_shout": "sprites/leonidas_i_2_shout.png",
        "lord_el_melloi_ii_2_joy": "sprites/lord_el_melloi_ii_2_joy.png",
        "lord_el_melloi_ii_2_normal": "sprites/lord_el_melloi_ii_2_normal.png",
        "lord_el_melloi_ii_2_shout": "sprites/lord_el_melloi_ii_2_shout.png",
        "marie_2_joy": "sprites/marie_2_joy.png",
        "martha_2_joy": "sprites/martha_2_joy.png",
        "martha_2_normal": "sprites/martha_2_normal.png",
        "mash_3_12": "sprites/mash_3_12.png",
        "mash_3_13": "sprites/mash_3_13.png",
        "mash_3_14": "sprites/mash_3_14.png",
        "mash_3_6": "sprites/mash_3_6.png",
        "mash_3_anger": "sprites/mash_3_anger.png",
        "mash_3_joy": "sprites/mash_3_joy.png",
        "mash_3_normal": "sprites/mash_3_normal.png",
        "mash_3_shout": "sprites/mash_3_shout.png",
        "mash_3_shy": "sprites/mash_3_shy.png",
        "mash_3_sorrow": "sprites/mash_3_sorrow.png",
        "mata_hari_3_joy": "sprites/mata_hari_3_joy.png",
        "mata_hari_3_normal": "sprites/mata_hari_3_normal.png",
        "medea_lily_1_joy": "sprites/medea_lily_1_joy.png",
        "medea_lily_1_normal": "sprites/medea_lily_1_normal.png",
        "medea_lily_1_shout": "sprites/medea_lily_1_shout.png",
        "medea_lily_1_shy": "sprites/medea_lily_1_shy.png",
        "medea_lily_1_sorrow": "sprites/medea_lily_1_sorrow.png",
        "medjed_1_4": "sprites/medjed_1_4.png",
        "medjed_1_normal": "sprites/medjed_1_normal.png",
        "medjed_1_shout": "sprites/medjed_1_shout.png",
        "medusa_1_normal": "sprites/medusa_1_normal.png",
        "medusa_1_sorrow": "sprites/medusa_1_sorrow.png",
        "merlin_2_anger": "sprites/merlin_2_anger.png",
        "merlin_2_joy": "sprites/merlin_2_joy.png",
        "merlin_2_normal": "sprites/merlin_2_normal.png",
        "merlin_2_shout": "sprites/merlin_2_shout.png",
        "merlin_2_shy": "sprites/merlin_2_shy.png",
        "merlin_2_sorrow": "sprites/merlin_2_sorrow.png",
        "mordred_2_anger": "sprites/mordred_2_anger.png",
        "mordred_2_joy": "sprites/mordred_2_joy.png",
        "mordred_2_normal": "sprites/mordred_2_normal.png",
        "mordred_2_shout": "sprites/mordred_2_shout.png",
        "mordred_2_sorrow": "sprites/mordred_2_sorrow.png",
        "nero_2_anger": "sprites/nero_2_anger.png",
        "nero_2_joy": "sprites/nero_2_joy.png",
        "nero_2_normal": "sprites/nero_2_normal.png",
        "nero_2_shout": "sprites/nero_2_shout.png",
        "nero_2_shy": "sprites/nero_2_shy.png",
        "nero_2_sorrow": "sprites/nero_2_sorrow.png",
        "nightingale_2_9": "sprites/nightingale_2_9.png",
        "nightingale_2_anger": "sprites/nightingale_2_anger.png",
        "nightingale_2_joy": "sprites/nightingale_2_joy.png",
        "nightingale_2_normal": "sprites/nightingale_2_normal.png",
        "nightingale_2_shout": "sprites/nightingale_2_shout.png",
        "nightingale_2_shy": "sprites/nightingale_2_shy.png",
        "noah_3_joy": "sprites/noah_3_joy.png",
        "noah_3_normal": "sprites/noah_3_normal.png",
        "noah_3_shout": "sprites/noah_3_shout.png",
        "okada_izou_1_12": "sprites/okada_izou_1_12.png",
        "okada_izou_1_9": "sprites/okada_izou_1_9.png",
        "okada_izou_1_normal": "sprites/okada_izou_1_normal.png",
        "okada_izou_1_sorrow": "sprites/okada_izou_1_sorrow.png",
        "ozymandias_3_joy": "sprites/ozymandias_3_joy.png",
        "ozymandias_3_normal": "sprites/ozymandias_3_normal.png",
        "ozymandias_3_shy": "sprites/ozymandias_3_shy.png",
        "ozymandias_3_6": "sprites/ozymandias_3_6.png",
        "ozymandias_3_shout": "sprites/ozymandias_3_shout.png",
        "ozymandias_3_anger": "sprites/ozymandias_3_anger.png",
        "phantom_2_joy": "sprites/phantom_2_joy.png",
        "pirate_1_normal": "sprites/pirate_1_normal.png",
        "pirates_1_normal": "sprites/pirates_1_normal.png",
        "queen_draco_shadow_1_shadow": "sprites/queen_draco_shadow_1_shadow.png",
        "sakata_kintoki_2_anger": "sprites/sakata_kintoki_2_anger.png",
        "sakata_kintoki_2_joy": "sprites/sakata_kintoki_2_joy.png",
        "sakata_kintoki_2_normal": "sprites/sakata_kintoki_2_normal.png",
        "sakata_kintoki_2_shout": "sprites/sakata_kintoki_2_shout.png",
        "sakata_kintoki_2_shy": "sprites/sakata_kintoki_2_shy.png",
        "sakata_kintoki_2_sorrow": "sprites/sakata_kintoki_2_sorrow.png",
        "scathach_2_anger": "sprites/scathach_2_anger.png",
        "scathach_2_joy": "sprites/scathach_2_joy.png",
        "scathach_2_normal": "sprites/scathach_2_normal.png",
        "scathach_2_shout": "sprites/scathach_2_shout.png",
        "scathach_2_sorrow": "sprites/scathach_2_sorrow.png",
        "sita_2_joy": "sprites/sita_2_joy.png",
        "sita_2_shout": "sprites/sita_2_shout.png",
        "tamamo_no_mae_2_joy": "sprites/tamamo_no_mae_2_joy.png",
        "tamamo_no_mae_2_normal": "sprites/tamamo_no_mae_2_normal.png",
        "tamamo_no_mae_2_shout": "sprites/tamamo_no_mae_2_shout.png",
        "tamamo_no_mae_2_sorrow": "sprites/tamamo_no_mae_2_sorrow.png",
        "tiamat_1_7": "sprites/tiamat_1_7.png",
        "tiamat_1_joy": "sprites/tiamat_1_joy.png",
        "tiamat_1_normal": "sprites/tiamat_1_normal.png",
        "tiamat_1_shout": "sprites/tiamat_1_shout.png",
        "tiamat_1_sorrow": "sprites/tiamat_1_sorrow.png",
        "vlad_iii_1_joy": "sprites/vlad_iii_1_joy.png",
        "vlad_iii_1_normal": "sprites/vlad_iii_1_normal.png",
        # used for non_story
        "captain_1_anger": "sprites/captain_1_anger.png",
        "captain_1_joy": "sprites/captain_1_joy.png",
        "captain_1_normal": "sprites/captain_1_normal.png",
        "captain_1_shout": "sprites/captain_1_shout.png",
        "captain_1_shy": "sprites/captain_1_shy.png",
        "queen_draco_1_anger": "sprites/queen_draco_1_anger.png",
        "queen_draco_1_joy": "sprites/queen_draco_1_joy.png",
        "queen_draco_1_normal": "sprites/queen_draco_1_normal.png",
        "queen_draco_1_shout": "sprites/queen_draco_1_shout.png",
        # big beastvi/s
        "beast_vis_1_big_0": "sprites/beast_vis_1_big_0.png",
        "beast_vis_1_big_7": "sprites/beast_vis_1_big_7.png",
        "beast_vis_1_big_anger": "sprites/beast_vis_1_big_anger.png",
        "beast_vis_1_big_joy": "sprites/beast_vis_1_big_joy.png",
        "beast_vis_1_big_normal": "sprites/beast_vis_1_big_normal.png",
        "beast_vis_1_big_shy": "sprites/beast_vis_1_big_shy.png",
        "beast_vis_1_big_sorrow": "sprites/beast_vis_1_big_sorrow.png",
        "beast_vis_1_big_shadow": "sprites/beast_vis_1_big_shadow.png"
    }


    sprites_to_download = {
        "intro": [
            "queen_draco_1_normal",
            "queen_draco_1_anger",
            "queen_draco_1_shout",
            "queen_draco_1_joy"
        ],
        "642_0": [
            "merlin_2_silhouette",
            "mash_3_6",
            "mash_3_anger",
            "mash_3_joy",
            "mash_3_normal",
            "merlin_2_joy",
            "merlin_2_normal"
        ],
        "642_1": [
            "first_hassan_2_silhouette",
            "amadeus_2_joy",
            "amadeus_2_shy",
            "carmilla_1_normal",
            "deon_2_anger",
            "deon_2_shout",
            "elisabeth_1_shout",
            "elisabeth_1_sorrow",
            "first_hassan_2_anger",
            "first_hassan_2_normal",
            "gilles_de_rais_2_joy",
            "jeanne_alter_2_shout",
            "jeanne_alter_2_shy",
            "jeanne_darc_2_anger",
            "jeanne_darc_2_normal",
            "kiyohime_2_shout",
            "marie_2_joy",
            "martha_2_joy",
            "martha_2_normal",
            "mash_3_6",
            "mash_3_joy",
            "mash_3_normal",
            "mash_3_shout",
            "merlin_2_joy",
            "merlin_2_normal",
            "merlin_2_shout",
            "merlin_2_shy",
            "phantom_2_joy",
            "vlad_iii_1_joy",
            "vlad_iii_1_normal",
        ],
        "642_4": [
            "elisabeth_1_joy",
            "first_hassan_2_normal",
            "jeanne_darc_2_normal",
            "marie_2_joy",
            "mash_3_anger",
            "merlin_2_anger",
            "merlin_2_shout"
        ],
        "643_0": [
            "first_hassan_2_normal",
            "first_hassan_2_shout",
            "mash_3_14",
            "mash_3_6",
            "mash_3_joy",
            "merlin_2_joy",
            "merlin_2_normal",
            "nero_2_joy",
            "nero_2_normal",
            "nero_2_shout",
            "nero_2_shy",
            "nero_2_sorrow"
        ],
        "643_1": [
            "altera_2_joy",
            "altera_2_normal",
            "boudica_2_joy",
            "boudica_2_normal",
            "boudica_2_shout",
            "boudica_2_sorrow",
            "caesar_2_joy",
            "caesar_2_shout",
            "caligula_2_anger",
            "caligula_2_shout",
            "first_hassan_2_normal",
            "leonidas_i_2_joy",
            "leonidas_i_2_normal",
            "leonidas_i_2_shout",
            "lord_el_melloi_ii_2_normal",
            "lord_el_melloi_ii_2_shout",
            "mash_3_6",
            "mash_3_joy",
            "mash_3_normal",
            "merlin_2_normal",
            "nero_2_anger",
            "nero_2_joy",
            "nero_2_normal",
            "nero_2_shout",
            "nero_2_sorrow"       
        ],
        "643_4": [
            "altera_2_joy",
            "first_hassan_2_normal",
            "lord_el_melloi_ii_2_joy",
            "lord_el_melloi_ii_2_normal",
            "mash_3_anger",
            "merlin_2_joy",
            "merlin_2_normal",
            "nero_2_joy",
            "nero_2_normal",
            "nero_2_shout"
        ],
        "644_0": [
            "atalante_1_normal",
            "blackbeard_3_anger",
            "blackbeard_3_joy",
            "blackbeard_3_shout",
            "drake_2_joy",
            "drake_2_normal",
            "drake_2_shout",
            "first_hassan_2_normal",
            "mash_3_6",
            "mash_3_anger",
            "mash_3_shy",
            "merlin_2_shy",
            "pirate_1_normal",
            "pirates_1_normal"
        ],
        "644_1": [
            "atalante_1_normal",
            "blackbeard_3_shout",
            "blackbeard_3_sorrow",
            "drake_2_joy",
            "drake_2_normal",
            "drake_2_shout",
            "drake_2_sorrow",
            "first_hassan_2_shout",
            "first_hassan_2_sorrow",
            "heracles_1_shout",
            "mash_3_14",
            "mash_3_anger",
            "medea_lily_1_joy",
            "medea_lily_1_normal",
            "medea_lily_1_shout",
            "medea_lily_1_shy",
            "medea_lily_1_sorrow",
            "merlin_2_joy",
            "merlin_2_normal",
            "pirate_1_normal",
            "pirates_1_normal"
        ],
        "644_4": [
            "atalante_1_normal",
            "blackbeard_3_joy",
            "blackbeard_3_normal",
            "blackbeard_3_shout",
            "blackbeard_3_sorrow",
            "drake_2_anger",
            "drake_2_joy",
            "drake_2_normal",
            "first_hassan_2_normal",
            "mash_3_14",
            "medea_lily_1_joy",
            "merlin_2_joy",
            "merlin_2_normal",
            "pirates_1_normal"
        ],
        "645_0": [
            "first_hassan_2_normal",
            "mash_3_anger",
            "mash_3_joy",
            "merlin_2_anger",
            "merlin_2_joy",
            "mordred_2_anger",
            "mordred_2_joy",
            "mordred_2_normal",
            "mordred_2_shout",
            "mordred_2_sorrow",
            "tamamo_no_mae_2_joy",
            "tamamo_no_mae_2_normal",
            "tamamo_no_mae_2_shout",
            "tamamo_no_mae_2_sorrow"
        ],
        "645_1": [
            "artoria_2_anger",
            "artoria_2_normal",
            "artoria_2_sorrow",
            "first_hassan_2_joy",
            "jack_2_joy",
            "jack_2_normal",
            "mash_3_6",
            "merlin_2_joy",
            "mordred_2_joy",
            "mordred_2_normal",
            "mordred_2_shout",
            "mordred_2_sorrow",
            "tamamo_no_mae_2_sorrow"
        ],
        "645_4": [
            "artoria_2_normal",
            "first_hassan_2_normal",
            "jack_2_joy",
            "jack_2_normal",
            "mash_3_anger",
            "mash_3_joy",
            "merlin_2_joy",
            "merlin_2_normal",
            "mordred_2_anger",
            "mordred_2_normal",
            "mordred_2_sorrow",
            "tamamo_no_mae_2_joy",
            "tamamo_no_mae_2_normal" 
        ],
        "646_0": [
            "first_hassan_2_joy",
            "first_hassan_2_normal",
            "mash_3_anger",
            "mash_3_joy",
            "merlin_2_joy",
            "nightingale_2_9",
            "nightingale_2_anger",
            "nightingale_2_joy",
            "nightingale_2_normal",
            "nightingale_2_shy",
            "scathach_2_anger",
            "scathach_2_joy",
            "scathach_2_normal",
            "sita_2_joy",
            "sita_2_shout"
        ],
        "646_1": [
            "arjuna_2_anger",
            "arjuna_2_joy",
            "arjuna_2_normal",
            "arjuna_2_shout",
            "arjuna_2_sorrow",
            "cu_chulainn_alter_1_joy",
            "cu_chulainn_alter_1_normal",
            "cu_chulainn_alter_1_shout",
            "cu_chulainn_alter_shadow_1_shadow",
            "karna_2_joy",
            "karna_2_normal",
            "karna_2_sorrow",
            "mash_3_6",
            "mash_3_shout",
            "scathach_2_anger",
            "scathach_2_joy",
            "scathach_2_normal",
            "scathach_2_shout",
            "scathach_2_sorrow"
        ],
        "646_4": [
            "arjuna_2_normal",
            "karna_2_joy",
            "mash_3_anger",
            "merlin_2_anger",
            "merlin_2_shout",
            "nightingale_2_anger",
            "nightingale_2_shout",
            "scathach_2_joy",
            "sita_2_joy"      
        ],
        "647_0": [
            "cursed_arm_3_normal",
            "cursed_arm_3_shout",
            "da_vinci_2_joy",
            "da_vinci_2_normal",
            "da_vinci_2_shout",
            "first_hassan_2_normal",
            "first_hassan_2_sorrow",
            "georgios_3_anger",
            "georgios_3_joy",
            "georgios_3_shout",
            "jacques_de_molay_1_20",
            "jacques_de_molay_1_anger",
            "jacques_de_molay_1_normal",
            "jacques_de_molay_1_shout",
            "jacques_de_molay_1_sorrow",
            "jacques_de_molay_shadow_1_shadow",
            "mash_3_14",
            "mash_3_6",
            "mash_3_anger",
            "mata_hari_3_normal",
            "medusa_1_normal",
            "medusa_1_sorrow",
            "merlin_2_anger",
            "merlin_2_normal",
            "okada_izou_1_12",
            "okada_izou_1_9",
            "okada_izou_1_normal",
            "okada_izou_1_sorrow"
        ],
        "647_1": [
            "first_hassan_2_normal",
            "jacques_de_molay_1_10",
            "jacques_de_molay_1_17",
            "jacques_de_molay_1_anger",
            "jacques_de_molay_1_shout",
            "jacques_de_molay_shadow_1_shadow",
            "mash_3_joy",
            "medjed_1_normal",
            "medjed_1_shout",
            "merlin_2_joy"
        ],
        "647_4": [
            "cursed_arm_3_normal",
            "da_vinci_2_joy",
            "first_hassan_2_shout",
            "jacques_de_molay_1_joy",
            "mash_3_anger",
            "mash_3_joy",
            "mata_hari_3_joy",
            "medjed_1_4",
            "medjed_1_normal",
            "merlin_2_anger",
            "ozymandias_3_joy",
            "ozymandias_3_normal",
            "ozymandias_3_shy"
        ],
        "648_0": [
            "first_hassan_2_shout",
            "lancelot_2_normal",
            "lancelot_2_shout",
            "mash_3_6",
            "mash_3_anger",
            "mash_3_shy",
            "merlin_2_joy",
            "queen_draco_shadow_1_shadow",
            "sakata_kintoki_2_anger",
            "sakata_kintoki_2_joy",
            "sakata_kintoki_2_normal",
            "sakata_kintoki_2_shout",
            "sakata_kintoki_2_shy",
            "sakata_kintoki_2_sorrow",
            "tiamat_1_7",
            "tiamat_1_joy",
            "tiamat_1_normal",
            "tiamat_1_shout"
        ],
        "648_1": [
            "enkidu_2_joy",
            "enkidu_2_normal",
            "first_hassan_2_sorrow",
            "gilgamesh_2_anger",
            "gilgamesh_2_joy",
            "gilgamesh_2_normal",
            "gilgamesh_2_shout",
            "gilgamesh_2_shy",
            "gilgamesh_2_sorrow",
            "lancelot_2_normal",
            "mash_3_6",
            "mash_3_joy",
            "mash_3_normal",
            "merlin_2_joy",
            "merlin_2_sorrow",
            "queen_draco_shadow_1_shadow",
            "sakata_kintoki_2_joy",
            "sakata_kintoki_2_normal",
            "sakata_kintoki_2_shout",
            "sakata_kintoki_2_shy",
            "tiamat_1_7",
            "tiamat_1_joy",
            "tiamat_1_normal",
            "tiamat_1_sorrow"
        ],
        "648_4": [
            "beast_vis_1_0",
            "beast_vis_1_normal",
            "beast_vis_1_sorrow",
            "beast_vis_1_big_0",
            "beast_vis_1_big_normal",
            "beast_vis_1_big_sorrow",
            "enkidu_2_joy",
            "first_hassan_2_anger",
            "first_hassan_2_normal",
            "gilgamesh_2_sorrow",
            "lancelot_2_normal",
            "mash_3_12",
            "mash_3_14",
            "mash_3_anger",
            "mash_3_joy",
            "mash_3_shout",
            "merlin_2_anger",
            "merlin_2_joy",
            "merlin_2_normal",
            "merlin_2_shout",
            "sakata_kintoki_2_joy",
            "tiamat_1_joy",
            "tiamat_1_shout",
            "tiamat_1_sorrow" 
        ],
        "649_0": [
            "arthur_2_normal",
            "arthur_2_silhouette",
            "noah_3_silhouette",
            "arthur_2_8",
            "arthur_2_anger",
            "arthur_2_shout",
            "beast_vis_1_big_0",
            "beast_vis_1_big_7",
            "beast_vis_1_big_joy",
            "beast_vis_1_big_normal",
            "mash_3_6",
            "mash_3_anger",
            "mash_3_joy",
            "merlin_2_joy",
            "noah_3_joy",
            "noah_3_normal",
            "noah_3_shout"
        ],
        "649_1": [
            "arthur_2_joy",
            "arthur_2_shout",
            "beast_vis_1_big_0",
            "beast_vis_1_big_7",
            "beast_vis_1_big_anger",
            "beast_vis_1_big_joy",
            "beast_vis_1_big_normal",
            "beast_vis_1_big_shy",
            "beast_vis_1_big_sorrow",
            "beast_vis_1_sorrow",
            "first_hassan_2_normal",
            "first_hassan_2_sorrow",
            "mash_3_14",
            "mash_3_6",
            "mash_3_shout",
            "mash_3_sorrow",
            "merlin_2_anger"
        ],
        "649_6": [
            "arthur_2_8",
            "arthur_2_anger",
            "arthur_2_shout",
            "first_hassan_2_normal",
            "mash_3_13",
            "mash_3_6",
            "mash_3_anger",
            "mash_3_joy",
            "mash_3_normal",
            "merlin_2_joy",
            "merlin_2_normal",
            "merlin_2_shout",
            "merlin_2_sorrow",
            "noah_3_joy",
            "noah_3_normal"
        ]
    }
